### ISSUE TITLE
Control after change to code has multiple variants.

### ISSUE THREAD

**Issue by zakstucke** [gaucho-labs/leptos-hotkeys#106]
After the change to `code` rather than `key` values for keyboard events, control now has 2 separate variants that need to be added if you want a generic control binding, e.g. binding control + k:

`Control+k` -> `controlleft+keyk,controlright+keyk`

Maybe this needs to be a special case and internally managed when `control` is included?

I also don't think the change from `key` to `code` is documented in the [readme](https://github.com/gaucho-labs/leptos-hotkeys?tab=readme-ov-file#keybinding-grammar) properly, I only worked it out from the changelog.

**Comment by mondeja** [comment]
Would you mind opening a PR to update that part of the README?

**Comment by mondeja** [comment]
IMO, seems a bit strange to have an exception for `control -> controleft,controlright`. What about other like `alt -> altright,altleft` or `shift -> shiftright,shiftleft`?

**Comment by zakstucke** [comment]
No problem and thanks! 

Just pr'd the readme change.
