### ISSUE TITLE
example/demo is not working correctly.

### ISSUE THREAD

**Issue by phillipbaird** [gaucho-labs/leptos-hotkeys#136]
The "use_key" feature flag has not been added in the Cargo.toml for the example/demo package.

It looks like in August the demo was updated to use keys instead of codes.  However when the use_key feature was introduced in September the feature flag was not added to the demo's Cargo.toml resulting in the hotkeys "s" and "6" not working.

The fix looks to be just to add the "use_key" feature flag.

Have run out of time tonight to test the ssr-demo but this issue might also be happening there.

**Comment by friendlymatthew** [comment]
Hey @phillipbaird -- thanks for flagging and investigating this issue.

> The fix looks to be just to add the "use_key" feature flag.

If you want, do you want to push a commit up for this? That would be greatly appreciated

**Comment by phillipbaird** [comment]
Hi @friendlymatthew - What's the story with the trunk build artifacts in /examples/demo/dist (under git control) - do you want those included in the PR?

**Comment by friendlymatthew** [comment]
Yes, that would be great.

**Comment by friendlymatthew** [comment]
@all-contributors please add @phillipbaird for code
