### ISSUE TITLE
Global Hotkeys setup.

### ISSUE THREAD

**Issue by phillipbaird** [gaucho-labs/leptos-hotkeys#39]
Hi Matthew,

Had to take your crate for a spin after seeing the demo you did at the monthly Leptos meeting.  Nice.

Just wondering if the following is the expected way to setup global shortcuts?

```rust
view! {
    <HotkeysProvider>
        {
            // Global shortcut to switch between Light and Dark themes.
            use_hotkeys!(("alt+t") => move |_| {
                set_mode.set(if mode() == ColorMode::Dark { ColorMode::Light } else { ColorMode::Dark })
            });
        }
        <Router>
            ...
        </Router>
    </HotkeysProvider>
}
```

It just felt a bit odd having to put a block of code like this into the markup.  I couldn't see where else to put it as the user could initially hit any route so it didn't seem to make sense to setup the globals within the route components themselves.  Is there a better way of doing this?

Thanks.

**Comment by friendlymatthew** [comment]
> Just wondering if the following is the expected way to setup global shortcuts? It just felt a bit odd having to put a block of code like this into the markup. I couldn't see where else to put it as the user could initially hit any route so it didn't seem to make sense to setup the globals within the route components themselves. Is there a better way of doing this?

Hey Phillip-- for a client side rendered project, this approach is the best way if you want to preserve the global hotkeys upon a page reload. However once #40 is up, there *should* be a more elegant approach.

For server side rendered projects, you can declare global hotkeys inside *any* component. Thanks to the [Leptos SSR life cycle.](https://book.leptos.dev/ssr/22_life_cycle.html)

Let me know if you have any other thoughts or questions! I hope you enjoy the library 🤠

**Comment by friendlymatthew** [comment]
Oh! One last thing, for any commands with `alt`, the pressed key sequence matters as pressing `T` then `alt` fires the hotkey, but pressing `alt` then `T` produces a different key value †. I'm going to fix this weird side effect issue in #35. But for now:

```rust
use_hotkeys!(("alt+t,†") => move |_| { ... });
```

works.

**Comment by phillipbaird** [comment]
My only other thought is the construction of the context could be separated from the component - similar to the way the leptos-meta crate does things. So you could then do this...

```rust
provide_hotkeys_context();

// Global shortcut to switch between Light and Dark themes.
use_hotkeys!(("alt+t") => move |_| {
    set_mode.set(if mode() == ColorMode::Dark { ColorMode::Light } else { ColorMode::Dark })
});

view! {
    <Hotkeys>
        <Router>
            ...
        </Router>
    </Hotkeys>
}
```

Just noting the idea to appease my OCD, as I'm yet to figure out if there's any value to it.

Oh BTW, I could not reproduce the problem with alt+t. It seems to work both ways for me. Am on Linux and got the same result in Firefox and Chrome.

**Comment by friendlymatthew** [comment]
@all-contributors add @phillipbaird for bug
