### ISSUE TITLE
Investigate `Alt` + `Key` sideeffect behavior for: Macos

### ISSUE THREAD

**Issue by friendlymatthew** [gaucho-labs/leptos-hotkeys#41]
`ALT` + `T` yields †. The current logic isn't able to process these special characters accordingly. 
<img width="298" alt="Screen Shot 2024-03-01 at 10 21 16 AM" src="https://github.com/gaucho-labs/leptos-hotkeys/assets/38759997/13c093bf-5169-4297-9943-4f52b4763e6d">

**Comment by mondeja** [comment]
See https://angular.io/guide/event-binding#binding-to-keyboard-events

**Comment by friendlymatthew** [comment]
Closing since `code` :)
