### ISSUE TITLE
Hotkeys prevent typing the unmodified key into input fields.

### ISSUE THREAD

**Issue by phillipbaird** [gaucho-labs/leptos-hotkeys#42]
In the following example we setup a hotkey for ctrl+g.
If you now try and type the letter g into the text input field you will find the letter is not entered.

```rust
#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/leptos-scratch.css"/>
        <Title text="Welcome to Leptos"/>

        <HotkeysProvider>
          {
            use_hotkeys!(("ctrl+g") => move |_| {
              logging::log!("hotkey pressed!");
            });
          }
          <input type="text" />
        </HotkeysProvider>
    }
}
```

The problem appears to be in use_hotkeys.rs.  In function is_hotkey_match(), event.prevent_default() is being called if just the key matches rather than if the modifers & key match.  Changing this so that event.prevent_default() is only called if the function result is true looks like it should fix this issue.

```rust
            let keys_match = hotkey.keys.iter().all(|key| {
                if let Some(event) = pressed_keyset.get_mut(key) {
                    event.prevent_default();
                    true
                } else {
                    false
                }
            });

            modifiers_match && keys_match
```
 
 needs to be something like...
 
```rust
             let keys_match = hotkey.keys.iter().all(|key| {
                if let Some(event) = pressed_keyset.get_mut(key) {
                    true
                } else {
                    false
                }
            });

            let is_match = modifiers_match && keys_match;
            if is_match { 
                 event.prevent_default(); 
            }
            is_match
```

**Comment by friendlymatthew** [comment]
Hey @phillipbaird thanks for this catch! Yes, this is a bug and we should be firing the `event.prevent_default()` when the modifiers and keys match. 

The *problem* with keys not registering when focusing on an `<input />` can be solveable. I ran into this problem with [leptos_kbar](https://github.com/gaucho-labs/leptos-kbar/blob/main/src/search/kbar_search.rs#L24-L47). Upon focus on an input, you'll need to toggle out of the scope that you're currently in. That is you'll need to dedicate a scope for input typing.

So `on:focus` and `on:blur` will need some logic.
