### ISSUE TITLE
Add checks and formatting

### ISSUE THREAD

**Issue by mondeja** [gaucho-labs/leptos-hotkeys#54]
A proper CI of a Rust library would tipically expect to contain as minimum a `cargo check` and a `cargo clippy` execution.

**Comment by mondeja** [comment]
I've added the `chore` label to track these types of internal improvements that are not library enhancements (covered by `improvements` label).

**Comment by friendlymatthew** [comment]
@all-contributors please add @JustBobinAround  for code

**Comment by friendlymatthew** [comment]
@all-contributors please add @JustBobinAround for code
