### ISSUE TITLE
Missing `0.1.4` and `0.1.5` changelog entries

### ISSUE THREAD

**Issue by mondeja** [gaucho-labs/leptos-hotkeys#80]
Seems that these versions have not been added to changelog.

**Comment by mondeja** [comment]
Seems to me that this is the unique blocker for the final release of v0.2.0. Are you interested in opening a PR soon @friendlymatthew?

**Comment by friendlymatthew** [comment]
Shoot -- I forgot to open a PR. I just pushed to main with the 0.1.4 and 0.1.5 entries as well as the `ev::keydown` changes

**Comment by mondeja** [comment]
It's enough, thanks!
