### ISSUE TITLE
Remove `prelude` module

### ISSUE THREAD

**Issue by mondeja** [gaucho-labs/leptos-hotkeys#83]
Since you can now use `use leptos_hotkeys::*;` it no longer makes sense to maintain the `prelude` module as will bring the same funcionality. Leptos itself uses this approach. Seems to me that the `prelude` module is a misconception about the best practices exporting modules from a library.

This would be a breaking change.

Thoughs about this @friendlymatthew? If you agree, do you think that this could be included in v0.2.0 or we should wait for v0.3.0?

**Comment by friendlymatthew** [comment]
I agree that we should remove this. I don't think this will be that bad of a change, and can be something we implement now.
